[theme]
primaryColor = "#FF4B4B"

backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
base = "light"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true

[runner]
magicEnabled = true

[client.showstreamrunnerWarning]
showWarning = false